export default interface NominatimResponse {
	place_id: number;
	licence: string;
	osm_type: string;
	osm_id: number;
	lat: string;
	lon: string;
	category: string;
	type: string;
	place_rank: number;
	importance: number;
	addresstype: string;
	name: string;
	display_name: string;
	address: {
		continent?: string;
		country?: string;
		country_code?: string;
		region?: string;
		state?: string;
		state_district?: string;
		county?: string;
		municipality?: string;
		city?: string;
		town?: string;
		village?: string;
		city_district?: string;
		district?: string;
		borough?: string;
		suburb?: string;
		subdivision?: string;
		hamlet?: string;
		croft?: string;
		neighbourhood?: string;
		allotments?: string;
		quarter?: string;
		residential?: string;
		farm?: string;
		farmyard?: string;
		industrial?: string;
		commercial?: string;
		retail?: string;
		road?: string;
		house_number?: string;
		postcode?: string;
		[key: string]: string | undefined;
	};
	boundingbox: [string, string, string, string];
}