enum InspectionStatusCodes {
	REQUEST_REGISTERED = 1,
	TECHNICAL_MANAGER_ACCEPTED,
	TECHNICAL_MANAGER_REJECTED,
	INSPECTING,
	NOT_APPROVED,
	SENDING,
	APPROVED_SABAF,
	SELF_DECLARATION_REGISTERED,
	SELF_DECLARATION_EXPIRED,
	TECHNICAL_MANAGER_CHECKING_SELF_DECLARATION,
	SENDING_IMAGES,
	IMAGES_SENT,
	HAS_SABAF,
	RECIEVED_SABAF,
}

export default InspectionStatusCodes;
